//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marlabskiranam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mvc_users
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "Firstname required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "LastName required")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Password required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Password doesn't match")]
        [DataType(DataType.Password)]
        [DisplayName("Retype Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Enter exact email")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email")]
        public string EmailID { get; set; }

        [Required(ErrorMessage = "By deafult we will choose your gender as others")]
        public string Gender { get; set; }

        [DisplayName("DOB")]
        [Required(ErrorMessage = "Enter if you are a human")]
        [DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }
    }
}
